ジョブにprettierを追加

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,7 +23,25 @@ jobs:
   #     - name: Run ESLint with auto-fix
   #       run: npx eslint src/ --fix
   
-    
+  
+  prettier:
+    name: Check Code Formatting
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: Run Prettier
+        run: npm run prettier -- --check
+
   # E2E-tests:
   #   runs-on: ubuntu-latest
   #   timeout-minutes: 30
@@ -496,221 +514,201 @@ jobs:
   #       run: docker-compose down
 
       
-  deploy:
-    runs-on: ubuntu-latest
-    # needs:
-    #   - lint
-    #   - E2E-tests
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - lint
+  #     - E2E-tests
+  #     - prettier
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20'
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '20'
     
-      - name: Install Firebase CLI
-        run: npm install -g firebase-tools
+  #     - name: Install Firebase CLI
+  #       run: npm install -g firebase-tools
 
-      - name: Check Firebase CLI
-        run: firebase --version
+  #     - name: Check Firebase CLI
+  #       run: firebase --version
 
 
-      - name: Set up Firebase credentials
-        run: |
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > functions/.env
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
+  #     - name: Set up Firebase credentials
+  #       run: |
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > functions/.env
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
 
-      - name: Create .env file and keys
-        run: |
-          echo "VITE_HTTPS=${{ secrets.VITE_HTTPS }}" >> .env
-          echo "FIREBASE_EMULATOR_HOST=${{ secrets.FIREBASE_EMULATOR_HOST }}" >> .env
-          echo "VITE_REACT_APP_API_URL=${{ secrets.VITE_REACT_APP_API_URL }}" >> .env
-          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
-          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
-          echo "VITE_REACT_APP_VAPID_KEY=${{ secrets.VITE_REACT_APP_VAPID_KEY }}" >> .env
-          echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> .env
-          echo "VITE_REACT_APP_VAPID_KEY=${{ secrets.VITE_REACT_APP_VAPID_KEY}}" >> .env
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_API_KEY=${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_APP_ID=${{ secrets.VITE_REACT_APP_FIREBASE_APP_ID }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.VITE_REACT_APP_FIREBASE_DATABASE_URL }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.VITE_REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_REACT_APP_FIREBASE_MEASUREMENT_ID }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
-          echo "VITE_REACT_APP_TEST_EMAIL=${{ secrets.VITE_REACT_APP_TEST_EMAIL }}" >> .env
-          echo "VITE_REACT_APP_TEST2_EMAIL=${{ secrets.VITE_REACT_APP_TEST2_EMAIL }}" >> .env
-          echo "VITE_REACT_APP_TEST_PASSWORD=${{ secrets.VITE_REACT_APP_TEST_PASSWORD }}" >> .env
-          echo "VITE_REACT_APP_TES2_PASSWORD=${{ secrets.VITE_REACT_APP_TEST2_PASSWORD }}" >> .env
-          echo "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}" >> .env
-          echo "VITE_HOST=${{ secrets.VITE_HOST }}" >> .env
-          echo "VITE_PORT=${{ secrets.VITE_PORT }}" >> .env
-          echo "VITE_PLAYWRIGHT_BASE_URL=${{ secrets.VITE_PLAYWRIGHT_BASE_URL }}" >> .env
-          echo "VITE_CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.VITE_CLOUDFLARE_TUNNEL_TOKEN }}" >> .env
-          echo "VITE_CLOUDFLARE_API_TOKEN=${{ secrets.VITE_CLOUDFLARE_API_TOKEN }}" >> .env
-          echo "TUNNEL_ID=${{ secrets.TUNNEL_ID }}" >> .env
-          echo "HOST=${{ secrets.HOST }}" >> .env
-          echo "PORT=${{ secrets.PORT }}" >> .env
-          echo "DEPLOY_PORT=${{ secrets.DEPLOY_PORT }}" >> .env
+  #     - name: Create .env file and keys
+  #       run: |
+  #         echo "VITE_HTTPS=${{ secrets.VITE_HTTPS }}" >> .env
+  #         echo "FIREBASE_EMULATOR_HOST=${{ secrets.FIREBASE_EMULATOR_HOST }}" >> .env
+  #         echo "VITE_REACT_APP_API_URL=${{ secrets.VITE_REACT_APP_API_URL }}" >> .env
+  #         echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
+  #         echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
+  #         echo "VITE_REACT_APP_VAPID_KEY=${{ secrets.VITE_REACT_APP_VAPID_KEY }}" >> .env
+  #         echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> .env
+  #         echo "VITE_REACT_APP_VAPID_KEY=${{ secrets.VITE_REACT_APP_VAPID_KEY}}" >> .env
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_API_KEY=${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_APP_ID=${{ secrets.VITE_REACT_APP_FIREBASE_APP_ID }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.VITE_REACT_APP_FIREBASE_DATABASE_URL }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.VITE_REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_REACT_APP_FIREBASE_MEASUREMENT_ID }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
+  #         echo "VITE_REACT_APP_TEST_EMAIL=${{ secrets.VITE_REACT_APP_TEST_EMAIL }}" >> .env
+  #         echo "VITE_REACT_APP_TEST2_EMAIL=${{ secrets.VITE_REACT_APP_TEST2_EMAIL }}" >> .env
+  #         echo "VITE_REACT_APP_TEST_PASSWORD=${{ secrets.VITE_REACT_APP_TEST_PASSWORD }}" >> .env
+  #         echo "VITE_REACT_APP_TES2_PASSWORD=${{ secrets.VITE_REACT_APP_TEST2_PASSWORD }}" >> .env
+  #         echo "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}" >> .env
+  #         echo "VITE_HOST=${{ secrets.VITE_HOST }}" >> .env
+  #         echo "VITE_PORT=${{ secrets.VITE_PORT }}" >> .env
+  #         echo "VITE_PLAYWRIGHT_BASE_URL=${{ secrets.VITE_PLAYWRIGHT_BASE_URL }}" >> .env
+  #         echo "VITE_CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.VITE_CLOUDFLARE_TUNNEL_TOKEN }}" >> .env
+  #         echo "VITE_CLOUDFLARE_API_TOKEN=${{ secrets.VITE_CLOUDFLARE_API_TOKEN }}" >> .env
+  #         echo "TUNNEL_ID=${{ secrets.TUNNEL_ID }}" >> .env
+  #         echo "HOST=${{ secrets.HOST }}" >> .env
+  #         echo "PORT=${{ secrets.PORT }}" >> .env
+  #         echo "DEPLOY_PORT=${{ secrets.DEPLOY_PORT }}" >> .env
 
   
-      - name: Decode to json file
-        run: |
-          echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> functions/.env
-          echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> .env
-          echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee ./serviceAccountKey.json > /dev/null
-          echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee ./functions/serviceAccountKey.json > /dev/null
-          echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee ./firebase/serviceAccountKey.json > /dev/null
-          echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee .env > /dev/null
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> ./functions/.env
-        env:
-          CHJY7_SERVICE_ACCOUNT: ${{ secrets.CHJY7_SERVICE_ACCOUNT }}
+  #     - name: Decode to json file
+  #       run: |
+  #         echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> functions/.env
+  #         echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> .env
+  #         echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee ./serviceAccountKey.json > /dev/null
+  #         echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee ./functions/serviceAccountKey.json > /dev/null
+  #         echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee ./firebase/serviceAccountKey.json > /dev/null
+  #         echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee .env > /dev/null
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> ./functions/.env
+  #       env:
+  #         CHJY7_SERVICE_ACCOUNT: ${{ secrets.CHJY7_SERVICE_ACCOUNT }}
 
   
           
-      - name: Authenticate with Service Account
-        run: |
-          echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee /tmp/serviceAccountKey.json > /dev/null
-          gcloud auth activate-service-account --key-file=/tmp/serviceAccountKey.json
-          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/serviceAccountKey.json" >> $GITHUB_ENV
+  #     - name: Authenticate with Service Account
+  #       run: |
+  #         echo "${{ secrets.CHJY7_SERVICE_ACCOUNT }}" | base64 --decode | sudo tee /tmp/serviceAccountKey.json > /dev/null
+  #         gcloud auth activate-service-account --key-file=/tmp/serviceAccountKey.json
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/serviceAccountKey.json" >> $GITHUB_ENV
       
 
-      - name: Debug JSON output
-        run: |
-          cat ./serviceAccountKey.json
-          jq '.' ./serviceAccountKey.json || echo "Invalid JSON format"
+  #     - name: Debug JSON output
+  #       run: |
+  #         cat ./serviceAccountKey.json
+  #         jq '.' ./serviceAccountKey.json || echo "Invalid JSON format"
 
 
-      - name: Set GOOGLE_APPLICATION_CREDENTIALS
-        run: echo "GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json" >> $GITHUB_ENV
+  #     - name: Set GOOGLE_APPLICATION_CREDENTIALS
+  #       run: echo "GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json" >> $GITHUB_ENV
   
            
-      - name: Debug GOOGLE_APPLICATION_CREDENTIALS
-        run: echo "$GOOGLE_APPLICATION_CREDENTIALS"
-             cat ./serviceAccountKey.json
-             cat $GOOGLE_APPLICATION_CREDENTIALS
-             file ./serviceAccountKey.json
+  #     - name: Debug GOOGLE_APPLICATION_CREDENTIALS
+  #       run: echo "$GOOGLE_APPLICATION_CREDENTIALS"
+  #            cat ./serviceAccountKey.json
+  #            cat $GOOGLE_APPLICATION_CREDENTIALS
+  #            file ./serviceAccountKey.json
 
 
-      - name: Set Firebase Config (Port)
-        run: firebase functions:config:set server.port=6080
+  #     - name: Set Firebase Config (Port)
+  #       run: firebase functions:config:set server.port=6080
 
         
-      - name: Use production firebase.json
-        run: cp firebase.prod.json firebase.json
+  #     - name: Use production firebase.json
+  #       run: cp firebase.prod.json firebase.json
 
             
-      - name: Copy to Dockerfile
-        run: cp Deployfile Dockerfile
+  #     - name: Copy to Dockerfile
+  #       run: cp Deployfile Dockerfile
 
 
-      - name: Copy to vite.congig
-        run: cp deploy.js vite.config.mjs
+  #     - name: Copy to vite.congig
+  #       run: cp deploy.js vite.config.mjs
 
 
-      - name: Copy to Docker-compose
-        run: cp deploy.yml docker-compose.yml
+  #     - name: Copy to Docker-compose
+  #       run: cp deploy.yml docker-compose.yml
 
             
-      - name: Install dependencies
-        run: |
-          npm install
+  #     - name: Install dependencies
+  #       run: |
+  #         npm install
 
 
-      - name: Install functons dependencies 
-        run: |
-          cd functions
-          npm install
+  #     - name: Install functons dependencies 
+  #       run: |
+  #         cd functions
+  #         npm install
       
           
-      - name: Authenticate with Google Cloud
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.CHJY7_SERVICE_ACCOUNT }}
+  #     - name: Authenticate with Google Cloud
+  #       uses: google-github-actions/auth@v1
+  #       with:
+  #         credentials_json: ${{ secrets.CHJY7_SERVICE_ACCOUNT }}
 
 
 
-      - name: Set up Google Cloud SDK
-        uses: google-github-actions/setup-gcloud@v2
-        with:
-          project_id: ${{ secrets.GCP_PROJECT_ID }}
+  #     - name: Set up Google Cloud SDK
+  #       uses: google-github-actions/setup-gcloud@v2
+  #       with:
+  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
           
 
 
-      - name: Authenticate Docker with Artifact Registry
-        run: |
-          gcloud auth configure-docker us-central1-docker.pkg.dev
+  #     - name: Authenticate Docker with Artifact Registry
+  #       run: |
+  #         gcloud auth configure-docker us-central1-docker.pkg.dev
 
       
-      # - name: Delete Container Redistly
-      #   run: |
-      #     gcloud container images delete gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcf --force-delete-tags --quiet
+
+  #     - name: Build and push Docker image for API3
+  #       run: |
+  #         docker buildx build --push \
+  #           -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/api3:latest .
 
 
-      # - name: Update Container Redistly
-      #   run: |
-      #     firebase functions:config:set gcr.url=us-central1-docker.pkg.dev
-      #     firebase deploy --only functions --force
+  #     - name: Deploy API3 to Cloud Run
+  #       run: |
+  #         gcloud run deploy api3 \
+  #           --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/api3:latest \
+  #           --region=us-central1 \
+  #           --platform=managed \
+  #           --allow-unauthenticated
 
 
-
-      - name: Build and push Docker image for API3
-        run: |
-          docker buildx build --push \
-            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/api3:latest .
-
-
-      - name: Deploy API3 to Cloud Run
-        run: |
-          gcloud run deploy api3 \
-            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/api3:latest \
-            --region=us-central1 \
-            --platform=managed \
-            --allow-unauthenticated
+  #     - name: Build and push Docker image to GC Docker for App2
+  #       run: |
+  #         docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/app2:$GITHUB_SHA .
+  #         docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/app2:$GITHUB_SHA
 
 
-      - name: Build and push Docker image to GC Docker for App2
-        run: |
-          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/app2:$GITHUB_SHA .
-          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/app2:$GITHUB_SHA
+  #     - name: Deploy App2 to Cloud Run
+  #       run: |
+  #         gcloud run deploy app2 \
+  #           --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/app2:$GITHUB_SHA \
+  #           --region us-central1 \
+  #           --platform managed \
+  #           --allow-unauthenticated \
+  #           --set-env-vars=FIREBASE_CONFIG='{"projectId":"${{ secrets.VITE_REACT_APP_FIREBASE_PROJECT_ID }}"}'
 
 
-      - name: Deploy App2 to Cloud Run
-        run: |
-          gcloud run deploy app2 \
-            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/app2:$GITHUB_SHA \
-            --region us-central1 \
-            --platform managed \
-            --allow-unauthenticated \
-            --set-env-vars=FIREBASE_CONFIG='{"projectId":"${{ secrets.VITE_REACT_APP_FIREBASE_PROJECT_ID }}"}'
-
-
-      - name: Set Firebase Project
-        run: |
-          firebase use reminder3-65e84
+  #     - name: Set Firebase Project
+  #       run: |
+  #         firebase use reminder3-65e84
 
           
-      # - name: Deploy To Firebase functions
-      #   run: |
-      #     firebase deploy --only functions --project reminder3-65e84 --debug 
+  #     - name: Deploy To Firebase functions
+  #       run: |
+  #         firebase deploy --only functions --project reminder3-65e84 --debug 
 
-      #   env:
-      #     GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json
+  #       env:
+  #         GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json
 
-
-      # - name: Deploy To Firebase hosting
-      #   run: |
-      #     firebase deploy --only hosting --project reminder3-65e84 --debug
-
-      #   env:
-      #     GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json
-
-
-          
+    
 
   # docker-hub:
   #   runs-on: ubuntu-latest
