修正

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -227,6 +227,28 @@ jobs:
           printf -- "${{ secrets.VITE_SERVER_CERT }}" > server.cert.pem
           printf -- "${{ secrets.VITE_SERVER_KEY }}" > server.key.pem
 
+      - name: Start ngrok and fetch URL
+        run: |
+          ngrok http 3000 > ngrok.log 2>&1 &
+          sleep 5
+          NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
+          if [ -n "$NGROK_URL" ]; then
+            echo "Ngrok URL fetched: $NGROK_URL"
+            echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV
+          else
+            echo "Error: Failed to fetch ngrok URL"
+            cat ngrok.log
+            exit 1
+          fi
+        env:
+          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
+  
+      - name: Use Ngrok URL
+        run: |
+          echo "Ngrok URL is ${{ env.NGROK_URL }}"
+        env:
+          NGROK_URL: ${{ env.NGROK_URL }}
+          
       - name: Debug .env file contents
         run: cat .env
         
@@ -237,21 +259,20 @@ jobs:
         run: |
           echo "VITE_NGROK_AUTH_TOKEN=${{ secrets.VITE_NGROK_AUTH_TOKEN }}"
           ngrok authtoken ${{ secrets.VITE_NGROK_AUTH_TOKEN }}
-  
+
+      - name: Entrypoint
+        run: ./entrypoint.sh
+             chmod +x ./entrypoint.sh
+
       - name: Build Docker image (App)
         run: docker build -t app:latest .
 
-      - name: Fetch Ngrok URL
-        run: |
-          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
-          echo "Ngrok URL fetched: $NGROK_URL"
-          echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV
+      # - name: Fetch Ngrok URL
+      #   run: |
+      #     NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
+      #     echo "Ngrok URL fetched: $NGROK_URL"
+      #     echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV
       
-      - name: Use Ngrok URL
-        run: |
-          echo "Ngrok URL is ${{ env.NGROK_URL }}"
-        env:
-          NGROK_URL: ${{ env.NGROK_URL }}
 
       - name: Run Playwright tests
         run: |
