fix problem does not display applications

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -432,135 +432,135 @@ jobs:
       - name: Teardown
         run: docker-compose down
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs:
-      - lint
-      - E2E-tests
-      - prettier
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - lint
+  #     - E2E-tests
+  #     - prettier
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20'
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '20'
 
-      - name: Install Firebase CLI
-        run: npm install -g firebase-tools@latest
+  #     - name: Install Firebase CLI
+  #       run: npm install -g firebase-tools@latest
 
-      - name: Check Firebase CLI
-        run: firebase --version
+  #     - name: Check Firebase CLI
+  #       run: firebase --version
 
-      - name: Set up Firebase credentials
-        run: |
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > functions/.env
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
+  #     - name: Set up Firebase credentials
+  #       run: |
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > functions/.env
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
 
-      - name: Create .env file and keys
-        run: |
-          echo "VITE_HTTPS=${{ secrets.VITE_HTTPS }}" >> .env
-          echo "FIREBASE_EMULATOR_HOST=${{ secrets.FIREBASE_EMULATOR_HOST }}" >> .env
-          echo "VITE_REACT_APP_API_URL=${{ secrets.VITE_REACT_APP_API_URL }}" >> .env
-          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
-          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
-          echo "VITE_REACT_APP_VAPID_KEY=${{ secrets.VITE_REACT_APP_VAPID_KEY }}" >> .env
-          echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> .env
-          echo "VITE_REACT_APP_VAPID_KEY=${{ secrets.VITE_REACT_APP_VAPID_KEY}}" >> .env
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_API_KEY=${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_APP_ID=${{ secrets.VITE_REACT_APP_FIREBASE_APP_ID }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.VITE_REACT_APP_FIREBASE_DATABASE_URL }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.VITE_REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_REACT_APP_FIREBASE_MEASUREMENT_ID }}" >> .env
-          echo "VITE_REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
-          echo "VITE_REACT_APP_TEST_EMAIL=${{ secrets.VITE_REACT_APP_TEST_EMAIL }}" >> .env
-          echo "VITE_REACT_APP_TEST2_EMAIL=${{ secrets.VITE_REACT_APP_TEST2_EMAIL }}" >> .env
-          echo "VITE_REACT_APP_TEST_PASSWORD=${{ secrets.VITE_REACT_APP_TEST_PASSWORD }}" >> .env
-          echo "VITE_REACT_APP_TEST2_PASSWORD=${{ secrets.VITE_REACT_APP_TEST2_PASSWORD }}" >> .env
-          echo "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}" >> .env
-          echo "VITE_HOST=${{ secrets.VITE_HOST }}" >> .env
-          echo "VITE_PORT=${{ secrets.VITE_PORT }}" >> .env
-          echo "VITE_PLAYWRIGHT_BASE_URL=${{ secrets.VITE_PLAYWRIGHT_BASE_URL }}" >> .env
-          echo "VITE_CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.VITE_CLOUDFLARE_TUNNEL_TOKEN }}" >> .env
-          echo "VITE_CLOUDFLARE_API_TOKEN=${{ secrets.VITE_CLOUDFLARE_API_TOKEN }}" >> .env
-          echo "TUNNEL_ID=${{ secrets.TUNNEL_ID }}" >> .env
-          echo "HOST=${{ secrets.HOST }}" >> .env
-          echo "PORT=${{ secrets.PORT }}" >> .env
-          echo "DEPLOY_PORT=${{ secrets.DEPLOY_PORT }}" >> .env
+  #     - name: Create .env file and keys
+  #       run: |
+  #         echo "VITE_HTTPS=${{ secrets.VITE_HTTPS }}" >> .env
+  #         echo "FIREBASE_EMULATOR_HOST=${{ secrets.FIREBASE_EMULATOR_HOST }}" >> .env
+  #         echo "VITE_REACT_APP_API_URL=${{ secrets.VITE_REACT_APP_API_URL }}" >> .env
+  #         echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
+  #         echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
+  #         echo "VITE_REACT_APP_VAPID_KEY=${{ secrets.VITE_REACT_APP_VAPID_KEY }}" >> .env
+  #         echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> .env
+  #         echo "VITE_REACT_APP_VAPID_KEY=${{ secrets.VITE_REACT_APP_VAPID_KEY}}" >> .env
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_API_KEY=${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_APP_ID=${{ secrets.VITE_REACT_APP_FIREBASE_APP_ID }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.VITE_REACT_APP_FIREBASE_DATABASE_URL }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.VITE_REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_REACT_APP_FIREBASE_MEASUREMENT_ID }}" >> .env
+  #         echo "VITE_REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
+  #         echo "VITE_REACT_APP_TEST_EMAIL=${{ secrets.VITE_REACT_APP_TEST_EMAIL }}" >> .env
+  #         echo "VITE_REACT_APP_TEST2_EMAIL=${{ secrets.VITE_REACT_APP_TEST2_EMAIL }}" >> .env
+  #         echo "VITE_REACT_APP_TEST_PASSWORD=${{ secrets.VITE_REACT_APP_TEST_PASSWORD }}" >> .env
+  #         echo "VITE_REACT_APP_TEST2_PASSWORD=${{ secrets.VITE_REACT_APP_TEST2_PASSWORD }}" >> .env
+  #         echo "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}" >> .env
+  #         echo "VITE_HOST=${{ secrets.VITE_HOST }}" >> .env
+  #         echo "VITE_PORT=${{ secrets.VITE_PORT }}" >> .env
+  #         echo "VITE_PLAYWRIGHT_BASE_URL=${{ secrets.VITE_PLAYWRIGHT_BASE_URL }}" >> .env
+  #         echo "VITE_CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.VITE_CLOUDFLARE_TUNNEL_TOKEN }}" >> .env
+  #         echo "VITE_CLOUDFLARE_API_TOKEN=${{ secrets.VITE_CLOUDFLARE_API_TOKEN }}" >> .env
+  #         echo "TUNNEL_ID=${{ secrets.TUNNEL_ID }}" >> .env
+  #         echo "HOST=${{ secrets.HOST }}" >> .env
+  #         echo "PORT=${{ secrets.PORT }}" >> .env
+  #         echo "DEPLOY_PORT=${{ secrets.DEPLOY_PORT }}" >> .env
 
-      - name: Decode to json file
-        run: |
-          echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> functions/.env
-          echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> .env
-          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee ./serviceAccountKey.json > /dev/null
-          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee ./functions/serviceAccountKey.json > /dev/null
-          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee ./firebase/serviceAccountKey.json > /dev/null
-          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee .env > /dev/null
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV
-          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> ./functions/.env
-        env:
-          FIREBASE_SERVICE_ACCOUNT9: ${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}
+  #     - name: Decode to json file
+  #       run: |
+  #         echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> functions/.env
+  #         echo "VITE_FIREBASE_TOKEN=${{ secrets.VITE_FIREBASE_TOKEN }}" >> .env
+  #         echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee ./serviceAccountKey.json > /dev/null
+  #         echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee ./functions/serviceAccountKey.json > /dev/null
+  #         echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee ./firebase/serviceAccountKey.json > /dev/null
+  #         echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee .env > /dev/null
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> ./functions/.env
+  #       env:
+  #         FIREBASE_SERVICE_ACCOUNT9: ${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}
 
-      - name: Authenticate with Service Account
-        run: |
-          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee /tmp/serviceAccountKey.json > /dev/null
-          gcloud auth activate-service-account --key-file=/tmp/serviceAccountKey.json
-          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/serviceAccountKey.json" >> $GITHUB_ENV
+  #     - name: Authenticate with Service Account
+  #       run: |
+  #         echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}" | base64 --decode | sudo tee /tmp/serviceAccountKey.json > /dev/null
+  #         gcloud auth activate-service-account --key-file=/tmp/serviceAccountKey.json
+  #         echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/serviceAccountKey.json" >> $GITHUB_ENV
 
-      - name: Debug JSON output
-        run: |
-          cat ./serviceAccountKey.json
-          jq '.' ./serviceAccountKey.json || echo "Invalid JSON format"
+  #     - name: Debug JSON output
+  #       run: |
+  #         cat ./serviceAccountKey.json
+  #         jq '.' ./serviceAccountKey.json || echo "Invalid JSON format"
 
-      - name: Set GOOGLE_APPLICATION_CREDENTIALS
-        run: echo "GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json" >> $GITHUB_ENV
+  #     - name: Set GOOGLE_APPLICATION_CREDENTIALS
+  #       run: echo "GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json" >> $GITHUB_ENV
 
-      - name: Debug GOOGLE_APPLICATION_CREDENTIALS
-        run: echo "$GOOGLE_APPLICATION_CREDENTIALS"
-          cat ./serviceAccountKey.json
-          cat $GOOGLE_APPLICATION_CREDENTIALS
-          file ./serviceAccountKey.json
+  #     - name: Debug GOOGLE_APPLICATION_CREDENTIALS
+  #       run: echo "$GOOGLE_APPLICATION_CREDENTIALS"
+  #         cat ./serviceAccountKey.json
+  #         cat $GOOGLE_APPLICATION_CREDENTIALS
+  #         file ./serviceAccountKey.json
 
-      - name: Use production firebase.json
-        run: cp firebase.prod.json firebase.json
+  #     - name: Use production firebase.json
+  #       run: cp firebase.prod.json firebase.json
 
-      - name: Copy to Dockerfile
-        run: cp Deployfile Dockerfile
+  #     - name: Copy to Dockerfile
+  #       run: cp Deployfile Dockerfile
 
-      - name: Copy to vite.congig
-        run: cp deploy.js vite.config.mjs
+  #     - name: Copy to vite.congig
+  #       run: cp deploy.js vite.config.mjs
 
-      - name: Copy to Docker-compose
-        run: cp deploy.yml docker-compose.yml
+  #     - name: Copy to Docker-compose
+  #       run: cp deploy.yml docker-compose.yml
 
-      - name: Install dependencies
-        run: |
-          rm -rf package-lock.json node_modules
-          npm install
+  #     - name: Install dependencies
+  #       run: |
+  #         rm -rf package-lock.json node_modules
+  #         npm install
 
-      - name: Authenticate with Google Cloud
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}
+  #     - name: Authenticate with Google Cloud
+  #       uses: google-github-actions/auth@v1
+  #       with:
+  #         credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT9 }}
 
-      - name: Set up Google Cloud SDK
-        uses: google-github-actions/setup-gcloud@v2
-        with:
-          project_id: ${{ secrets.GCP_PROJECT_ID }}
+  #     - name: Set up Google Cloud SDK
+  #       uses: google-github-actions/setup-gcloud@v2
+  #       with:
+  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
 
-      - name: Build For Deploy
-        run: |
-          npm run build
+  #     - name: Build For Deploy
+  #       run: |
+  #         npm run build
 
-      - name: Deploy To Firebase
-        run: |
-          firebase deploy --only hosting
+  #     - name: Deploy To Firebase
+  #       run: |
+  #         firebase deploy --only hosting
 
-        env:
-          GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json
+  #       env:
+  #         GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json
 
   docker-hub:
     runs-on: ubuntu-latest
