修正

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -298,7 +298,12 @@ jobs:
           fi
 
       - name: Inspect my_custom_network
-        run: docker network inspect reminder_my_custom_network || echo "Network my_custom_network not found"
+        run: docker network inspect reminder_my_custom_network || echo "Network reminder_my_custom_network not found"
+
+
+      - name: Inspect cloudflared IP Address
+        run: docker exec app2 curl -v http://172.18.0.4
+
 
       # - name: Add app2 to /etc/hosts in cloudflared
       #   run: |
